import {Driver} from './types';

export const DRIVERS: {[index: number]: Driver} = {
  0: {abbreviation: 'SAI', firstName: 'Carlos', lastName: 'Sainz'},
  2: {abbreviation: 'RIC', firstName: 'Daniel', lastName: 'Ricciardo'},
  3: {abbreviation: 'ALO', firstName: 'Fernando', lastName: 'Alonso'},
  6: {abbreviation: 'RAI', firstName: 'Kimi', lastName: 'Raikkonen'},
  7: {abbreviation: 'HAM', firstName: 'Lewis', lastName: 'Hamilton'},
  8: {abbreviation: 'ERI', firstName: 'Marcus', lastName: 'Ericsson'},
  9: {abbreviation: 'VER', firstName: 'Max', lastName: 'Verstappen'},
  10: {abbreviation: 'HUL', firstName: 'Nico', lastName: 'Hulkenberg'},
  11: {abbreviation: 'MAG', firstName: 'Kevin', lastName: 'Magnussen'},
  12: {abbreviation: 'GRO', firstName: 'Romain', lastName: 'Grosjean'},
  13: {abbreviation: 'VET', firstName: 'Sebastian', lastName: 'Vettel'},
  14: {abbreviation: 'PER', firstName: 'Sergio', lastName: 'Perez'},
  15: {abbreviation: 'BOT', firstName: 'Valtteri', lastName: 'Bottas'},
  17: {abbreviation: 'OCO', firstName: 'Esteban', lastName: 'Ocon'},
  18: {abbreviation: 'VAN', firstName: 'Stoffel', lastName: 'Vandoorne'},
  19: {abbreviation: 'STR', firstName: 'Lance', lastName: 'Stroll'},
  20: {abbreviation: 'BAR', firstName: 'Arron', lastName: 'Barnes'},
  21: {abbreviation: 'GIL', firstName: 'Martin', lastName: 'Giles'},
  22: {abbreviation: 'MUR', firstName: 'Alex', lastName: 'Murray'},
  23: {abbreviation: 'ROT', firstName: 'Lucas', lastName: 'Roth'},
  24: {abbreviation: 'COR', firstName: 'Igor', lastName: 'Correia'},
  25: {abbreviation: 'LEV', firstName: 'Sophie', lastName: 'Levasseur'},
  26: {abbreviation: 'SCH', firstName: 'Jonas', lastName: 'Schiffer'},
  27: {abbreviation: 'FOR', firstName: 'Alain', lastName: 'Forest'},
  28: {abbreviation: 'LET', firstName: 'Jay', lastName: 'Letorneau'},
  29: {abbreviation: 'SAA', firstName: 'Esto', lastName: 'Saari'},
  30: {abbreviation: 'ATI', firstName: 'Yasar', lastName: 'Atiyeh'},
  31: {abbreviation: 'CAL', firstName: 'Callisto', lastName: 'Calabresi'},
  32: {abbreviation: 'IZU', firstName: 'Naota', lastName: 'Izum'},
  33: {abbreviation: 'CLA', firstName: 'Howard', lastName: 'Clarke'},
  34: {abbreviation: 'KAU', firstName: 'Wilheim', lastName: 'Kaufmann'},
  35: {abbreviation: 'LAU', firstName: 'Marie', lastName: 'Laursen'},
  36: {abbreviation: 'NIE', firstName: 'Flavio', lastName: 'Nieves'},
  58: {abbreviation: 'LEC', firstName: 'Charles', lastName: 'Leclerc'},
  59: {abbreviation: 'GAS', firstName: 'Pierre', lastName: 'Gasly'},
  60: {abbreviation: 'HAR', firstName: 'Brendon', lastName: 'Hartley'},
  61: {abbreviation: 'SIR', firstName: 'Sergey', lastName: 'Sirotkin'},
};
