export const INFRINGEMENTS: string[] = [
  'Blocking by slow driving',
  'Blocking by wrong way driving',
  'Reversing off the start line',
  'Big Collision',
  'Small Collision',
  'Collision failed to hand back position single',
  'Collision failed to hand back position multiple',
  'Corner cutting gained time',
  'Corner cutting overtake single',
  'Corner cutting overtake multiple',
  'Crossed pit exit lane',
  'Ignoring blue flags',
  'Ignoring yellow flags',
  'Ignoring drive through',
  'Too many drive throughs',
  'Drive through reminder serve within n laps',
  'Drive through reminder serve this lap',
  'Pit lane speeding',
  'Parked for too long',
  'Ignoring tyre regulations',
  'Too many penalties',
  'Multiple warnings',
  'Approaching disqualification',
  'Tyre regulations select single',
  'Tyre regulations select multiple',
  'Lap invalidated corner cutting',
  'Lap invalidated running wide',
  'Corner cutting ran wide gained time minor',
  'Corner cutting ran wide gained time significant',
  'Corner cutting ran wide gained time extreme',
  'Lap invalidated wall riding',
  'Lap invalidated flashback used',
  'Lap invalidated reset to track',
  'Blocking the pitlane',
  'Jump start',
  'Safety car to car collision',
  'Safety car illegal overtake',
  'Safety car exceeding allowed pace',
  'Virtual safety car exceeding allowed pace',
  'Formation lap below allowed speed',
  'Retired mechanical failure',
  'Retired terminally damaged',
  'Safety car falling too far back',
  'Black flag timer',
  'Unserved stop go penalty',
  'Unserved drive through penalty',
  'Engine component change',
  'Gearbox change',
  'League grid penalty',
  'Retry penalty',
  'Illegal time gain',
  'Mandatory pitstop',
];
