export const NATIONALITIES: string[] = [
  'American',       'Argentinean',   'Australian', 'Austrian',
  'Azerbaijani',    'Bahraini',      'Belgian',    'Bolivian',
  'Brazilian',      'British',       'Bulgarian',  'Cameroonian',
  'Canadian',       'Chilean',       'Chinese',    'Colombian',
  'Costa Rican',    'Croatian',      'Cypriot',    'Czech',
  'Danish',         'Dutch',         'Ecuadorian', 'English',
  'Emirian',        'Estonian',      'Finnish',    'French',
  'German',         'Ghanaian',      'Greek',      'Guatemalan',
  'Honduran',       'Hong Konger',   'Hungarian',  'Icelander',
  'Indian',         'Indonesian',    'Irish',      'Israeli',
  'Italian',        'Jamaican',      'Japanese',   'Jordanian',
  'Kuwaiti',        'Latvian',       'Lebanese',   'Lithuanian',
  'Luxembourger',   'Malaysian',     'Maltese',    'Mexican',
  'Monegasque',     'New Zealander', 'Nicaraguan', 'North Korean',
  'Northern Irish', 'Norwegian',     'Omani',      'Pakistani',
  'Panamanian',     'Paraguayan',    'Peruvian',   'Polish',
  'Portuguese',     'Qatari',        'Romanian',   'Russian',
  'Salvadoran',     'Saudi',         'Scottish',   'Serbian',
  'Singaporean',    'Slovakian',     'Slovenian',  'South Korean',
  'South African',  'Spanish',       'Swedish',    'Swiss',
  'Thai',           'Turkish',       'Uruguayan',  'Ukrainian',
  'Venezuelan',     'Welsh',
];
