export const PENALTIES: string[] = [
  'Drive through',
  'Stop Go',
  'Grid penalty',
  'Penalty reminder',
  'Time penalty',
  'Warning',
  'Disqualified',
  'Removed from formation lap',
  'Parked too long timer',
  'Tyre regulations',
  'This lap invalidated',
  'This and next lap invalidated',
  'This lap invalidated without reason',
  'This and next lap invalidated without reason',
  'This and previous lap invalidated',
  'This and previous lap invalidated without reason',
  'Retired',
  'Black flag timer',
];
