import {Track} from './types';

export const TRACKS: {[index: number]: Track} = {
  0: {name: 'Melbourne'},
  1: {name: 'Paul Ricard'},
  2: {name: 'Shanghai'},
  3: {name: 'Sakhir (Bahrain)'},
  4: {name: 'Catalunya'},
  5: {name: 'Monaco'},
  6: {name: 'Montreal'},
  7: {name: 'Silverstone'},
  8: {name: 'Hockenheim'},
  9: {name: 'Hungaroring'},
  10: {name: 'Spa'},
  11: {name: 'Monza'},
  12: {name: 'Singapore'},
  13: {name: 'Suzuka'},
  14: {name: 'Abu Dhabi'},
  15: {name: 'Texas'},
  16: {name: 'Brazil'},
  17: {name: 'Austria'},
  18: {name: 'Sochi'},
  19: {name: 'Mexico'},
  20: {name: 'Baku (Azerbaijan)'},
  21: {name: 'Sakhir Short'},
  22: {name: 'Silverstone Short'},
  23: {name: 'Texas Short'},
  24: {name: 'Suzuka Short'},
  25: {name: 'Hanoi'},
  26: {name: 'Zandvoort'},
  27: {name: 'Imola'},
  28: {name: 'Portimao'},
  29: {name: 'Jeddah'},
  30: {name: 'Miami'},
  31: {name: 'Las Vegas'},
  32: {name: 'Losail'},
};
