import {Track} from './types';

export const TRACKS: Track[] = [
  {name: 'Melbourne'},
  {name: 'Paul Ricard'},
  {name: 'Shanghai'},
  {name: 'Sakhir (Bahrain)'},
  {name: 'Catalunya'},
  {name: 'Monaco'},
  {name: 'Montreal'},
  {name: 'Silverstone'},
  {name: 'Hockenheim'},
  {name: 'Hungaroring'},
  {name: 'Spa'},
  {name: 'Monza'},
  {name: 'Singapore'},
  {name: 'Suzuka'},
  {name: 'Abu Dhabi'},
  {name: 'Texas'},
  {name: 'Brazil'},
  {name: 'Austria'},
  {name: 'Sochi'},
  {name: 'Mexico'},
  {name: 'Baku (Azerbaijan)'},
  {name: 'Sakhir Short'},
  {name: 'Silverstone Short'},
  {name: 'Texas Short'},
  {name: 'Suzuka Short'},
  {name: 'Hanoi'},
  {name: 'Zandvoort'},
  {name: 'Imola'},
  {name: 'Portimao'},
  {name: 'Jeddah'},
];
