import {Track} from './types';

export const TRACKS: Track[] = [
  {name: 'Melbourne'},
  {name: 'Paul Ricard'},
  {name: 'Shanghai'},
  {name: 'Sakhir'},
  {name: 'Catalunya'},
  {name: 'Monaco'},
  {name: 'Montreal'},
  {name: 'Silverstone'},
  {name: 'Hockenheim'},
  {name: 'Hungaroring'},
  {name: 'Spa'},
  {name: 'Monza'},
  {name: 'Singapore'},
  {name: 'Suzuka'},
  {name: 'Abu Dhabi'},
  {name: 'Texas'},
  {name: 'Brazil'},
  {name: 'Austria'},
  {name: 'Sochi'},
  {name: 'Mexico'},
  {name: 'Baku'},
  {name: 'Sakhir (Short)'},
  {name: 'Silverstone (Short)'},
  {name: 'Texas (Short)'},
  {name: 'Suzuka (Short)'},
];
